[tool.poetry]
name = "hh-parser"
version = "0.1.0"
description = ""
authors = ["kot <bafomet2016vitt@gmail.com>"]
readme = "README.md"
packages = [{include = "hh_parser"}]

[tool.poetry.dependencies]
python = "^3.9"
psycopg2 = "^2.6"
pytest = "^6.0"
coverage = "^6.0"
requests = "^2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
